CREATE TABLE USERS (
	USER_ID			BIGINT(20)			NOT NULL	AUTO_INCREMENT,
	USER_USERNAME	VARCHAR(128)		NOT NULL	UNIQUE,
	USER_PASSWORD	VARCHAR(128)		NOT NULL,
	PRIMARY KEY(USER_ID)
);

CREATE TABLE PERMISSIONS (
	P_ID			BIGINT(20)			NOT NULL	AUTO_INCREMENT,
	P_DESC			TEXT				NOT NULL,
	PRIMARY KEY(P_ID)
);

CREATE TABLE GROUPS (
	G_ID			BIGINT(20)			NOT NULL	AUTO_INCREMENT,
	G_NAME			TEXT				NOT NULL,
	PRIMARY KEY(G_ID)
);

CREATE TABLE AUTHORIZATION (
	G_ID			BIGINT(20)			REFERENCES GROUPS(G_ID),
	P_ID			BIGINT(20)			REFERENCES PERMISSIONS(P_ID),
	PRIMARY KEY(G_ID, P_ID)
);

CREATE TABLE USERDATA (
	USER_ID			BIGINT(20)			REFERENCES USERS(USER_ID),
	NAME			TEXT				NOT NULL,
	SURNAME			TEXT				NOT NULL,
	ADDRESS			TEXT				NOT NULL,
	TELEPHONE		TEXT				NOT NULL,
	G_ID			BIGINT(20)			REFERENCES GROUPS(G_ID),
	PRIMARY KEY(USER_ID, G_ID)
);

CREATE TABLE PRODUCTS (
	PROD_ID			BIGINT(20)		NOT NULL PRIMARY KEY AUTO_INCREMENT,
	PROD_NAME		VARCHAR(256)	NOT NULL,
	PROD_DESC		TEXT			NOT NULL,
	PROD_PRICE		REAL			NOT NULL
);

CREATE TABLE cart (
	USER_ID		BIGINT(20)		NOT NULL		REFERENCES USERS(USER_ID),
	PROD_ID		BIGINT(20)		NOT NULL		REFERENCES PRODUCTS(PROD_ID),
	QTY			BIGINT(20)		NOT NULL,
    
	PRIMARY KEY(USER_ID, PROD_ID)
);

