CREATE TABLE IF NOT EXISTS BLOG_POST (
	POST_ID		BIGINT(20)	NOT NULL	AUTO_INCREMENT,
	POST_TITLE 	TEXT		NOT NULL,
	POST_DATA	TEXT		NOT NULL,
	PRIMARY KEY(POST_ID)
);

CREATE TABLE IF NOT EXISTS USERS (
	USER_ID			BIGINT(20)			NOT NULL	AUTO_INCREMENT,
	USER_USERNAME	VARCHAR(128)		NOT NULL	UNIQUE,
	USER_PASSWORD	VARCHAR(128)		NOT NULL,
	PRIMARY KEY(USER_ID)
);

CREATE TABLE IF NOT EXISTS PERMISSIONS (
	P_ID			BIGINT(20)			NOT NULL	AUTO_INCREMENT,
	P_DESC			TEXT				NOT NULL,
	PRIMARY KEY(P_ID)
);

CREATE TABLE IF NOT EXISTS GROUPS(
	G_ID			BIGINT(20)			NOT NULL	AUTO_INCREMENT,
	G_NAME			TEXT				NOT NULL,
	PRIMARY KEY(G_ID)
);

CREATE TABLE IF NOT EXISTS AUTHORIZATION (
	G_ID			BIGINT(20)			REFERENCES GROUPS(G_ID),
	P_ID			BIGINT(20)			REFERENCES PERMISSIONS(P_ID),
	PRIMARY KEY(G_ID, P_ID)
);

CREATE TABLE IF NOT EXISTS USERDATA (
	USER_ID			BIGINT(20)			REFERENCES USERS(USER_ID),
	NAME			TEXT				NOT NULL,
	SURNAME			TEXT				NOT NULL,
	ADDRESS			TEXT				NOT NULL,
	TELEPHONE		TEXT				NOT NULL,
	G_ID			BIGINT(20)			REFERENCES GROUPS(G_ID),
	PRIMARY KEY(USER_ID, G_ID)
);